name: C/C++ CI
env:
  SLOW_TESTS: 1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-check:
    name: Build and check
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install-cached-deps
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libev-dev libsodium-dev python3-nacl
        version: 1.1
    - name: make check
      run: make check
